services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/app
        working_dir: /app
        environment:
            COMPOSER_ALLOW_SUPERUSER: 1
        command: tail -f /dev/null
